id: P0D91FAE8
initial_creation_type: ocr
source_metadata:
  volumes:
    15b06d7d010647348b79715226c07d9f:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: གནོད་སྦྱིན་ནག་པོ་ཆེན་པོ་ལ་རིན་པོ་ཆེ་བསྟོད་པ།
      total_pages: 1902
      volume_number: 26
