id: P0D91FAE8
initial_creation_type: ocr
source_metadata:
  volumes:
    6f4a4cb3dd604407a4b3edfcfeff21f1:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: གནོད་སྦྱིན་ནག་པོ་ཆེན་པོ་ལ་རིན་པོ་ཆེ་བསྟོད་པ།
      total_pages: 1464
      volume_number: 47
